export const Paths = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  PROFILE_PERSONAL_INFO: '/profile/personal-info',
  PROFILE_SECTION: '/profile/:section',
  DATABASE_SCHEMAS: '/profile/database-schemas',
  SECURITY: '/profile/security',
  ADMIN: '/admin',
  ADMIN_SECTION: '/admin/:section',
  ADMIN_USERS: '/admin/users',
  ADMIN_MAINTENANCE: '/admin/maintenance',
  MODULES: '/modules/:moduleCode',
  WILDCARD: '*',
} as const
